# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ScrollableTab' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ScrollableTab
  pod 'ScrollTab'
  
  target 'ScrollableTabTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ScrollableTabUITests' do
    # Pods for testing
  end

end
